services:
  backend:
    image: lapis-dev-backend:latest
    environment:
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - BACKEND_PORT=${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    links:
      - database:${PGHOST}
  database:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_DB=${PGDATABASE}
      - PGPORT=${PGPORT}
    ports:
      - "${PGPORT}:${PGPORT}"
