services:
  database:
    image: postgres:14
    container_name: lapis-dev-database-1
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_DB=${PGDATABASE}
      - PGPORT=${PGPORT}
    ports:
      - "${PGPORT}:${PGPORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
