packages:
  - "apps/*"

catalog:
  "@nuxt/eslint": ^1.15.2
  eslint: ^9.39.2
  nuxt: ^4.4.2
  vue: ^3.5.32
  tailwindcss: ^4.2.2
  typescript: ^6.0.2
  vite: ^7.3.1

# tells pnpm never to run the installation/build scripts (preinstall, install, postinstall) for the specified dependencies
ignoredBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver
  - vue-demi

# block all post-install scripts across the entire project, EXCEPT for these packages
onlyBuiltDependencies:
  - "@intlify/vue-i18n-bridge"
  - "@intlify/vue-router-bridge"
  - better-sqlite3

# -------------------------
# Hoisting Rules
# -------------------------
# Elevates these specific dependencies to the root node_modules directory
publicHoistPattern:
  - "*@tailwindcss/vite*"
  - "@nuxtjs/mdc*"
  - "remark*"
  - "rehype*"
  - "unified*"
  - "unist*"
  - "parse5*"
  - "debug*"

# -------------------------
# Engine & Environment Settings
# -------------------------
engineStrict: true
packageManagerStrict: false
shellEmulator: true

# -------------------------
# Workspace Settings
# -------------------------
sharedWorkspaceLockfile: true

# -------------------------
# Security Policies
# -------------------------

# Enforce a 3-day (4320 minutes) cooldown period for all new packages
# 1 day = 1440, 3 days = 4320, 7 days = 10080
minimumReleaseAge: 4320

# Block transitive dependencies from using git repos or direct tarball URLs
blockExoticSubdeps: true

# Fail installation if a package loses its trusted publisher or provenance status
trustPolicy: no-downgrade
