packages:
  - apps/**

ignoredBuiltDependencies:
  - "@intlify/vue-i18n-bridge"
  - "@intlify/vue-router-bridge"
  - "@parcel/watcher"
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver
  - vue-demi

onlyBuiltDependencies:
  - better-sqlite3
